env = Environment(CPPPATH=[".", "../cuilien", "../depend/dawn/src"], CPPFLAGS="-std=c++14", CFLAGS="-std=c99", LIBPATH=["../cuilien/build", "../depend/dawn/build"])


# Source section
sources = Split("""
main.cpp
log/logger.cpp
comm/comm_server.cpp
comm/comm_client.cpp
comm/ip_comm_server.cpp
comm/ip_comm_client.cpp
""")


# Object section
objects = env.Object(source = sources)


# Target section
binary = env.Program(target = "bin", source = objects, LIBS = ["pthread", "cuilien", "dawn-log", "dawn-data"])

