env = Environment(CPPPATH=[".", "../cuilien"], CPPFLAGS="-std=c++11", CFLAGS="-std=c99", LIBPATH="../cuilien/build")


# Source section
sources = Split("""
main.cpp
""")


# Object section
objects = env.Object(source = sources)


# Target section
binary = env.Program(target = "bin", source = objects, LIBS = ["cuilien"])

